### PR TITLE
Fix links, inline image

### PR DESCRIPTION
**Pull request by glensc**

### CODE REVIEW

**Comment by glensc** [comment]
@markstory I guess you can just merge and archive the project.

**Comment by markstory** [comment]
> I guess you can just merge and archive the project.

Why? Does the inclued extension no longer work?

**Comment by glensc** [comment]
Doesn't compile for php7 nor php5.


```
/ # apk add php7-pear php7-dev alpine-sdk
/ # pecl install inclued-beta
...
/tmp/pear/temp/inclued/php_inclued.h:29:10: fatal error: ext/standard/php_smart_str.h: No such file or directory
 #include "ext/standard/php_smart_str.h"
...
```

tested with:
```
/ # php --version
PHP 7.1.33 (cli) (built: Oct 26 2019 06:32:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

/ # php --version
PHP 7.3.14 (cli) (built: Jan 27 2020 21:55:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies

/ # php --version
PHP 7.2.33 (cli) (built: Sep  5 2020 21:22:47) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

```
/ # apk add php5-pear php5-dev alpine-sdk autoconf automake
/ # ln -snf /usr/bin/php5 /usr/bin/php
/ # pecl install inclued-beta
...
/tmp/pear/temp/inclued/inclued_zend.c: In function 'inclued_get_zval_ptr':
/tmp/pear/temp/inclued/inclued_zend.c:24:73: error: 'zend_execute_data {aka struct _zend_execute_data}' has no member named 'Ts'
 #define INCLUED_EX_T(offset)     (*(temp_variable *)((char*)execute_data->Ts + offset))
                                                                         ^
```

tested with
```
/ # php5 --version
PHP 5.6.40 (cli) (built: Feb  1 2019 19:57:52)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
/ #
```

**Comment by glensc** [comment]
Archived doesn't mean the project can't be used. Just to show it's not maintained (it's archived).

**Pull request merged**
